### ISSUE TITLE
Incompatible with numpy==1.16.0

### ISSUE THREAD

**Issue by intsco** [albu/albumentations#161]
## 🐛 Bug

When installed with `pip`, incompatible versions of `numpy` and `skimage` may be installed.

## To Reproduce

1. `pip install -U albumentations`
2. `python`
3. `import albumentations`

```
root@11e08e49dff0:/app# pip install -U albumentations
Requirement already up-to-date: albumentations in /usr/local/lib/python3.6/dist-packages (0.1.10)
Requirement already satisfied, skipping upgrade: numpy>=1.11.1 in /usr/local/lib/python3.6/dist-packages (from albumentations) (1.16.0)
Requirement already satisfied, skipping upgrade: scipy in /usr/local/lib/python3.6/dist-packages (from albumentations) (1.2.0)
Requirement already satisfied, skipping upgrade: opencv-python in /usr/local/lib/python3.6/dist-packages (from albumentations) (4.0.0.21)
Requirement already satisfied, skipping upgrade: imgaug>=0.2.5 in /usr/local/lib/python3.6/dist-packages (from albumentations) (0.2.7)
Requirement already satisfied, skipping upgrade: scikit-image>=0.11.0 in /usr/local/lib/python3.6/dist-packages (from imgaug>=0.2.5->albumentations) (0.14.1)
Requirement already satisfied, skipping upgrade: six in /usr/local/lib/python3.6/dist-packages (from imgaug>=0.2.5->albumentations) (1.12.0)
Requirement already satisfied, skipping upgrade: matplotlib in /usr/local/lib/python3.6/dist-packages (from imgaug>=0.2.5->albumentations) (3.0.2)
Requirement already satisfied, skipping upgrade: Pillow in /usr/local/lib/python3.6/dist-packages (from imgaug>=0.2.5->albumentations) (5.4.1)
Requirement already satisfied, skipping upgrade: imageio in /usr/local/lib/python3.6/dist-packages (from imgaug>=0.2.5->albumentations) (2.4.1)
Requirement already satisfied, skipping upgrade: Shapely in /usr/local/lib/python3.6/dist-packages (from imgaug>=0.2.5->albumentations) (1.6.4.post2)
Requirement already satisfied, skipping upgrade: networkx>=1.8 in /usr/local/lib/python3.6/dist-packages (from scikit-image>=0.11.0->imgaug>=0.2.5->albumentations) (2.2)
Requirement already satisfied, skipping upgrade: PyWavelets>=0.4.0 in /usr/local/lib/python3.6/dist-packages (from scikit-image>=0.11.0->imgaug>=0.2.5->albumentations) (1.0.1)
Requirement already satisfied, skipping upgrade: dask[array]>=0.9.0 in /usr/local/lib/python3.6/dist-packages (from scikit-image>=0.11.0->imgaug>=0.2.5->albumentations) (1.0.0)
Requirement already satisfied, skipping upgrade: cloudpickle>=0.2.1 in /usr/local/lib/python3.6/dist-packages (from scikit-image>=0.11.0->imgaug>=0.2.5->albumentations) (0.6.1)
Requirement already satisfied, skipping upgrade: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->imgaug>=0.2.5->albumentations) (2.3.1)
Requirement already satisfied, skipping upgrade: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->imgaug>=0.2.5->albumentations) (1.0.1)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->imgaug>=0.2.5->albumentations) (2.7.5)
Requirement already satisfied, skipping upgrade: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib->imgaug>=0.2.5->albumentations) (0.10.0)
Requirement already satisfied, skipping upgrade: decorator>=4.3.0 in /usr/local/lib/python3.6/dist-packages (from networkx>=1.8->scikit-image>=0.11.0->imgaug>=0.2.5->albumentations) (4.3.0)
Requirement already satisfied, skipping upgrade: toolz>=0.7.3; extra == "array" in /usr/local/lib/python3.6/dist-packages (from dask[array]>=0.9.0->scikit-image>=0.11.0->imgaug>=0.2.5->albumentations) (0.9.0)
Requirement already satisfied, skipping upgrade: setuptools in /usr/local/lib/python3.6/dist-packages (from kiwisolver>=1.0.1->matplotlib->imgaug>=0.2.5->albumentations) (40.6.3)
root@11e08e49dff0:/app# python
Python 3.6.8 (default, Dec 24 2018, 19:24:27) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import albumentations
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/albumentations/__init__.py", line 5, in <module>
    from .core.composition import *
  File "/usr/local/lib/python3.6/dist-packages/albumentations/core/composition.py", line 11, in <module>
    from albumentations.imgaug.transforms import DualIAATransform
  File "/usr/local/lib/python3.6/dist-packages/albumentations/imgaug/transforms.py", line 1, in <module>
    import imgaug as ia
  File "/usr/local/lib/python3.6/dist-packages/imgaug/__init__.py", line 2, in <module>
    from imgaug.imgaug import *
  File "/usr/local/lib/python3.6/dist-packages/imgaug/imgaug.py", line 22, in <module>
    import skimage.draw
  File "/usr/local/lib/python3.6/dist-packages/skimage/__init__.py", line 167, in <module>
    from .util.dtype import (img_as_float32,
  File "/usr/local/lib/python3.6/dist-packages/skimage/util/__init__.py", line 8, in <module>
    from .arraycrop import crop
  File "/usr/local/lib/python3.6/dist-packages/skimage/util/arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name '_validate_lengths'
```

## Expected behavior

Working installation of the library

## Environment

 - Albumentations version:  (e.g., 0.1.8)
 - Python version: 3.6.8
 - OS (e.g., Linux): Ubuntu 16.04
 - How you installed albumentations: pip
 - Any other relevant information: docker

## Additional context

`pip install -U numpy==1.15.4` fixes the problem

**Comment by albu** [comment]
should be fixed in 0.1.11, please reopen if you are still issuing this

**Comment by alexionby** [comment]
`Numpy==1.16.2
albumentations==0.2.0`  
The same problem is back.

**Comment by Podidiving** [comment]
`numpy==1.17.0 albumentations==0.3.1`
Same problem
